/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.6.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral {
        metadataSources {
            mavenPom()
            artifact()
            ignoreGradleMetadataRedirection()
        }
    }
}

val jedisVersion = "7.5.3"
val javaFakerVersion = "1.0.2"
val snakeYamlVersion = "2.6"
val lombokVersion = "1.18.46"
val commonsLang3Version = "3.20.0"
val jacksonVersion = "2.22.1"
val slf4jVersion = "2.0.18"
val logbackVersion = "1.5.38"

val javaVersion = 21

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    // Source: https://mvnrepository.com/artifact/redis.clients/jedis
    implementation("redis.clients:jedis:$jedisVersion")
    // Source: https://mvnrepository.com/artifact/com.github.javafaker/javafaker
    implementation("com.github.javafaker:javafaker:$javaFakerVersion") {
    exclude(group = "org.yaml", module = "snakeyaml")
    }
    // Source: https://mvnrepository.com/artifact/org.yaml/snakeyaml
    implementation("org.yaml:snakeyaml:$snakeYamlVersion") {
    isTransitive = false
        artifact {
            name = "snakeyaml"
            type = "jar"
            extension = "jar"
        }
    }

    annotationProcessor ("org.projectlombok:lombok:$lombokVersion")
    implementation("org.projectlombok:lombok:$lombokVersion")
    // Source: https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
    implementation("com.fasterxml.jackson.core:jackson-databind:$jacksonVersion")
    // Source: https://mvnrepository.com/artifact/org.slf4j/slf4j-api
    implementation("org.slf4j:slf4j-api:$slf4jVersion")
    // Source: https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
    implementation("ch.qos.logback:logback-classic:$logbackVersion")
    // Source: https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
    implementation("org.apache.commons:commons-lang3:$commonsLang3Version")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(javaVersion)
    }
}

application {
    mainClass.set("com.example.app.Main")
}
